# Generated by Django 2.2.1 on 2019-05-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20190507_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_length',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
