# Generated by Django 2.2.1 on 2019-05-07 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
