# Generated by Django 2.2.1 on 2019-05-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='end_frame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='start_frame',
            field=models.IntegerField(default=0),
        ),
    ]
