# Generated by Django 2.2.1 on 2019-05-07 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20190507_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='active_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
