# Generated by Django 2.2.1 on 2019-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20190507_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeworkflow',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
