# Generated by Django 2.2.1 on 2019-05-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_routelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
